# Generated by Django 2.2.12 on 2020-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, help_text='应用名', max_length=40, null=True, verbose_name='应用名')),
                ('rule_text', models.TextField(blank=True, help_text='比赛规则', max_length=255, null=True, verbose_name='比赛规则')),
                ('is_show_userinfo', models.BooleanField(default=False, help_text='是否展示用户信息表单', verbose_name='展示用户表单')),
                ('userinfo_fields', models.CharField(blank=True, help_text='需要用户填写的字段#隔开', max_length=128, null=True, verbose_name='用户表单字段')),
                ('userinfo_field_names', models.CharField(blank=True, help_text='用户需要填写的表单字段label名称', max_length=128, null=True, verbose_name='用户表单label')),
                ('option_fields', models.CharField(blank=True, help_text='下拉框字段选项配置，#号隔开，每个字段由:h和，号组成。 如 option1:吃饭，喝水，睡觉#option2:上班，学习，看电影', max_length=128, null=True, verbose_name='下拉框字段')),
            ],
            options={
                'verbose_name': '应用配置信息',
                'verbose_name_plural': '应用配置信息',
            },
        ),
        migrations.CreateModel(
            name='BusinessAccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_index=True, help_text='邮箱', max_length=40, null=True, unique=True, verbose_name='邮箱')),
                ('company_name', models.CharField(blank=True, help_text='公司名称', max_length=60, null=True, verbose_name='公司名称')),
                ('company_type', models.IntegerField(choices=[(0, '互联网'), (1, '金融'), (2, '能源'), (3, '基础建设'), (4, '交通'), (5, '通信')], default=0, help_text='公司类型', verbose_name='公司类型')),
                ('company_description', models.TextField(blank=True, help_text='公司描述', null=True, verbose_name='公司描述')),
                ('company_username', models.CharField(blank=True, help_text='公司联系人', max_length=32, null=True, verbose_name='法人代表')),
                ('company_phone', models.CharField(blank=True, db_index=True, help_text='公司联系电话', max_length=16, null=True, verbose_name='联系电话')),
                ('company_location', models.TextField(blank=True, help_text='公司联系地址', null=True, verbose_name='公司位置')),
            ],
            options={
                'verbose_name': '出题账户',
                'verbose_name_plural': '出题账户',
            },
        ),
        migrations.CreateModel(
            name='BusinessAppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, help_text='应用名', max_length=40, null=True, verbose_name='应用名')),
                ('app_description', models.TextField(blank=True, help_text='应用描述', null=True, verbose_name='应用描述')),
            ],
            options={
                'verbose_name': '应用信息',
                'verbose_name_plural': '应用信息',
            },
        ),
        migrations.CreateModel(
            name='UserInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uii_name', models.CharField(blank=True, help_text='信息图片配置名称', max_length=32, null=True, verbose_name='配置名称')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=60, null=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, help_text='性别', max_length=60, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, help_text='年龄', max_length=60, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=60, null=True, verbose_name='手机号')),
                ('wxid', models.CharField(blank=True, help_text='微信号', max_length=60, null=True, verbose_name='微信号')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=60, null=True, verbose_name='邮箱')),
                ('pid', models.CharField(blank=True, help_text='身份证号', max_length=60, null=True, verbose_name='身份证号')),
                ('graduated_from', models.CharField(blank=True, help_text='毕业院校', max_length=60, null=True, verbose_name='毕业院校')),
                ('address', models.CharField(blank=True, help_text='联系地址', max_length=60, null=True, verbose_name='地址')),
                ('resume', models.CharField(blank=True, help_text='简历', max_length=60, null=True, verbose_name='简历')),
            ],
            options={
                'verbose_name': '用户信息图片配置',
                'verbose_name_plural': '用户信息图片配置',
            },
        ),
    ]
